# This file contains values from Cookiecutter

default_context:
  project_name: "fireplace"
  project_description: "Awesome `fireplace` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "fireplace"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "fireplace"
  email: "hello@fireplace.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
